# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from loop_controller.v1 import governance_pb2 as loop__controller_dot_v1_dot_governance__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in loop_controller/v1/governance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ToolGovernanceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateToolCall = channel.unary_unary(
                '/loop_controller.proto.v1.ToolGovernance/EvaluateToolCall',
                request_serializer=loop__controller_dot_v1_dot_governance__pb2.EvaluateToolCallRequest.SerializeToString,
                response_deserializer=loop__controller_dot_v1_dot_governance__pb2.EvaluateToolCallResponse.FromString,
                _registered_method=True)
        self.ResumeAfterApproval = channel.unary_unary(
                '/loop_controller.proto.v1.ToolGovernance/ResumeAfterApproval',
                request_serializer=loop__controller_dot_v1_dot_governance__pb2.ResumeAfterApprovalRequest.SerializeToString,
                response_deserializer=loop__controller_dot_v1_dot_governance__pb2.EvaluateToolCallResponse.FromString,
                _registered_method=True)
        self.WaitForApproval = channel.unary_stream(
                '/loop_controller.proto.v1.ToolGovernance/WaitForApproval',
                request_serializer=loop__controller_dot_v1_dot_governance__pb2.WaitForApprovalRequest.SerializeToString,
                response_deserializer=loop__controller_dot_v1_dot_governance__pb2.EvaluateToolCallResponse.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/loop_controller.proto.v1.ToolGovernance/GetHealth',
                request_serializer=loop__controller_dot_v1_dot_governance__pb2.HealthRequest.SerializeToString,
                response_deserializer=loop__controller_dot_v1_dot_governance__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ListPendingApprovals = channel.unary_unary(
                '/loop_controller.proto.v1.ToolGovernance/ListPendingApprovals',
                request_serializer=loop__controller_dot_v1_dot_governance__pb2.ListPendingApprovalsRequest.SerializeToString,
                response_deserializer=loop__controller_dot_v1_dot_governance__pb2.ListPendingApprovalsResponse.FromString,
                _registered_method=True)
        self.QueryAuditEvents = channel.unary_stream(
                '/loop_controller.proto.v1.ToolGovernance/QueryAuditEvents',
                request_serializer=loop__controller_dot_v1_dot_governance__pb2.QueryAuditEventsRequest.SerializeToString,
                response_deserializer=loop__controller_dot_v1_dot_governance__pb2.AuditEvent.FromString,
                _registered_method=True)
        self.Revoke = channel.unary_unary(
                '/loop_controller.proto.v1.ToolGovernance/Revoke',
                request_serializer=loop__controller_dot_v1_dot_governance__pb2.RevokeRequest.SerializeToString,
                response_deserializer=loop__controller_dot_v1_dot_governance__pb2.RevokeResponse.FromString,
                _registered_method=True)
        self.SetKillSwitch = channel.unary_unary(
                '/loop_controller.proto.v1.ToolGovernance/SetKillSwitch',
                request_serializer=loop__controller_dot_v1_dot_governance__pb2.SetKillSwitchRequest.SerializeToString,
                response_deserializer=loop__controller_dot_v1_dot_governance__pb2.KillSwitchResponse.FromString,
                _registered_method=True)
        self.GetRevocationList = channel.unary_unary(
                '/loop_controller.proto.v1.ToolGovernance/GetRevocationList',
                request_serializer=loop__controller_dot_v1_dot_governance__pb2.GetRevocationListRequest.SerializeToString,
                response_deserializer=loop__controller_dot_v1_dot_governance__pb2.RevocationListResponse.FromString,
                _registered_method=True)


class ToolGovernanceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EvaluateToolCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeAfterApproval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitForApproval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPendingApprovals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAuditEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Revoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetKillSwitch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRevocationList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolGovernanceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateToolCall': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateToolCall,
                    request_deserializer=loop__controller_dot_v1_dot_governance__pb2.EvaluateToolCallRequest.FromString,
                    response_serializer=loop__controller_dot_v1_dot_governance__pb2.EvaluateToolCallResponse.SerializeToString,
            ),
            'ResumeAfterApproval': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeAfterApproval,
                    request_deserializer=loop__controller_dot_v1_dot_governance__pb2.ResumeAfterApprovalRequest.FromString,
                    response_serializer=loop__controller_dot_v1_dot_governance__pb2.EvaluateToolCallResponse.SerializeToString,
            ),
            'WaitForApproval': grpc.unary_stream_rpc_method_handler(
                    servicer.WaitForApproval,
                    request_deserializer=loop__controller_dot_v1_dot_governance__pb2.WaitForApprovalRequest.FromString,
                    response_serializer=loop__controller_dot_v1_dot_governance__pb2.EvaluateToolCallResponse.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=loop__controller_dot_v1_dot_governance__pb2.HealthRequest.FromString,
                    response_serializer=loop__controller_dot_v1_dot_governance__pb2.HealthResponse.SerializeToString,
            ),
            'ListPendingApprovals': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPendingApprovals,
                    request_deserializer=loop__controller_dot_v1_dot_governance__pb2.ListPendingApprovalsRequest.FromString,
                    response_serializer=loop__controller_dot_v1_dot_governance__pb2.ListPendingApprovalsResponse.SerializeToString,
            ),
            'QueryAuditEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryAuditEvents,
                    request_deserializer=loop__controller_dot_v1_dot_governance__pb2.QueryAuditEventsRequest.FromString,
                    response_serializer=loop__controller_dot_v1_dot_governance__pb2.AuditEvent.SerializeToString,
            ),
            'Revoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Revoke,
                    request_deserializer=loop__controller_dot_v1_dot_governance__pb2.RevokeRequest.FromString,
                    response_serializer=loop__controller_dot_v1_dot_governance__pb2.RevokeResponse.SerializeToString,
            ),
            'SetKillSwitch': grpc.unary_unary_rpc_method_handler(
                    servicer.SetKillSwitch,
                    request_deserializer=loop__controller_dot_v1_dot_governance__pb2.SetKillSwitchRequest.FromString,
                    response_serializer=loop__controller_dot_v1_dot_governance__pb2.KillSwitchResponse.SerializeToString,
            ),
            'GetRevocationList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRevocationList,
                    request_deserializer=loop__controller_dot_v1_dot_governance__pb2.GetRevocationListRequest.FromString,
                    response_serializer=loop__controller_dot_v1_dot_governance__pb2.RevocationListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loop_controller.proto.v1.ToolGovernance', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loop_controller.proto.v1.ToolGovernance', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolGovernance(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EvaluateToolCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop_controller.proto.v1.ToolGovernance/EvaluateToolCall',
            loop__controller_dot_v1_dot_governance__pb2.EvaluateToolCallRequest.SerializeToString,
            loop__controller_dot_v1_dot_governance__pb2.EvaluateToolCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeAfterApproval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop_controller.proto.v1.ToolGovernance/ResumeAfterApproval',
            loop__controller_dot_v1_dot_governance__pb2.ResumeAfterApprovalRequest.SerializeToString,
            loop__controller_dot_v1_dot_governance__pb2.EvaluateToolCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitForApproval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/loop_controller.proto.v1.ToolGovernance/WaitForApproval',
            loop__controller_dot_v1_dot_governance__pb2.WaitForApprovalRequest.SerializeToString,
            loop__controller_dot_v1_dot_governance__pb2.EvaluateToolCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop_controller.proto.v1.ToolGovernance/GetHealth',
            loop__controller_dot_v1_dot_governance__pb2.HealthRequest.SerializeToString,
            loop__controller_dot_v1_dot_governance__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPendingApprovals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop_controller.proto.v1.ToolGovernance/ListPendingApprovals',
            loop__controller_dot_v1_dot_governance__pb2.ListPendingApprovalsRequest.SerializeToString,
            loop__controller_dot_v1_dot_governance__pb2.ListPendingApprovalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryAuditEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/loop_controller.proto.v1.ToolGovernance/QueryAuditEvents',
            loop__controller_dot_v1_dot_governance__pb2.QueryAuditEventsRequest.SerializeToString,
            loop__controller_dot_v1_dot_governance__pb2.AuditEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Revoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop_controller.proto.v1.ToolGovernance/Revoke',
            loop__controller_dot_v1_dot_governance__pb2.RevokeRequest.SerializeToString,
            loop__controller_dot_v1_dot_governance__pb2.RevokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetKillSwitch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop_controller.proto.v1.ToolGovernance/SetKillSwitch',
            loop__controller_dot_v1_dot_governance__pb2.SetKillSwitchRequest.SerializeToString,
            loop__controller_dot_v1_dot_governance__pb2.KillSwitchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRevocationList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop_controller.proto.v1.ToolGovernance/GetRevocationList',
            loop__controller_dot_v1_dot_governance__pb2.GetRevocationListRequest.SerializeToString,
            loop__controller_dot_v1_dot_governance__pb2.RevocationListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
